version: '3'
services:
  editor:
    build:
      context: .
      dockerfile: .docker/editor/Dockerfile
    image: editor_web
    ports:
      - "127.0.0.1:8383:80"
    volumes:
      - ./editor:/var/www/html/editor
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: nada_docker
      DB_USERNAME: nada_user
      DB_PASSWORD: nada_password      
  mysql:
      image: mysql:5.7
      #container_name: mysql-57
      restart: always
      volumes:
        - ./db_data:/var/lib/mysql
      ports:
        - 13306:3306
      environment:
        MYSQL_DATABASE: nada_docker
        MYSQL_USER: nada_user
        MYSQL_PASSWORD: nada_password
        MYSQL_ROOT_PASSWORD: root
